sudo: false
language: go
go:
  - 1.7
services:
  - redis-server
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=ratelimiter.coverprofile
  - goveralls -coverprofile=ratelimiter.coverprofile -service=travis-ci
